### ISSUE TITLE
Gene/mrna id while loading count data

### ISSUE THREAD

**Issue by abretaud** [gogepp/genoboo#27]
Getting this error with genoboo add transcriptome:

```
## WARNING: 2023-06-07T07:35:24.586Z TypeError: Cannot destructure property 'genomeId' of 'Genes.findOne(...)' as it is undefined.
    at getGenomeId (imports/api/transcriptomes/addTranscriptome.js:18:11)
    at Object.complete (imports/api/transcriptomes/addTranscriptome.js:46:24)
    at StringStreamer.ChunkStreamer.parseChunk (/shared/ifbstor1/galaxy/mutable-data/dependencies/_conda/envs/__genoboo@0.4.2/share/genoboo-0.4.2-0/programs/server/npm/node_modules/papaparse/papaparse.js:570:18)
    at StringStreamer._nextChunk (/shared/ifbstor1/galaxy/mutable-data/dependencies/_conda/envs/__genoboo@0.4.2/share/genoboo-0.4.2-0/programs/server/npm/node_modules/papaparse/papaparse.js:816:16)
    at StringStreamer.stream (/shared/ifbstor1/galaxy/mutable-data/dependencies/_conda/envs/__genoboo@0.4.2/share/genoboo-0.4.2-0/programs/server/npm/node_modules/papaparse/papaparse.js:801:16)
    at Object.CsvToJson [as parse] (/shared/ifbstor1/galaxy/mutable-data/dependencies/_conda/envs/__genoboo@0.4.2/share/genoboo-0.4.2-0/programs/server/npm/node_modules/papaparse/papaparse.js:251:19)
    at imports/api/transcriptomes/addTranscriptome.js:34:8
    at new Promise (<anonymous>)
    at parseKallistoTsv (imports/api/transcriptomes/addTranscriptome.js:31:7)
    at MethodInvocation.run (imports/api/transcriptomes/addTranscriptome.js:112:12)
    at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:94:12)
    at MethodInvocation.addTranscriptome (packages/mdg:validated-method/validated-method.js:57:23)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
```

Probably because the tsv file first column contains gene ids instead of mrna, I guess the loader could/should be able to use them (even if it's not super logical).

**Comment by mboudet** [comment]
We should manage the case where the gene is not found anyway
